language: rust

rust:
   - nightly-2018-05-06
   - nightly

matrix:
   allow_failures:
      - rust: nightly

install:
   - set -eo pipefail
   - pushd /tmp

   # Install DevkitARM
   - export DEVKITPRO="/opt/devkitpro"
   - export DEVKITARM="$DEVKITPRO/devkitARM"
   - export PATH="$PATH:$DEVKITARM/bin"
   - wget https://raw.githubusercontent.com/devkitPro/installer/master/perl/devkitARMupdate.pl
   - chmod +x devkitARMupdate.pl
   - ./devkitARMupdate.pl "$DEVKITPRO"

   # Install Xargo
   - cargo install xargo

   # Install Rust source
   - rustup component add rust-src

   - popd

script:
   - cd examples
   - export CC_3ds="arm-none-eabi-gcc"
   - export TARGET_CFLAGS="-mfloat-abi=hard -march=armv6k"
   - RUST_TARGET_PATH=$(pwd) xargo build --release
